/* XPM */
static char * ck_core_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 16 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s background	m black	c #949494949494",
"o	s iconGray1	m white	c #dededededede",
"O	s iconGray2	m white	c #bdbdbdbdbdbd",
"+	s topShadowColor	m white	c #bdbdbdbdbdbd",
"@	s iconColor2	m white	c white",
"#	s bottomShadowColor	m black	c #636363636363",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray4	m white	c #949494949494",
"&	s iconGray5	m black	c #737373737373",
"*	s iconGray6	m black	c #636363636363",
"=	s iconGray7	m black	c #424242424242",
"-	s iconGray8	m black	c #212121212121",
";	s iconColor3	m black	c red",
":	s iconColor4	m white	c green",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"     .....................................      ",
"    .......................................     ",
"    ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..     ",
"    ..XXXoooooooooooooooooooooooooooooXXX..     ",
"    ..XXXoooooooooooooooooooooooooooooXXX..     ",
"    ..XXXOOOOOOOOO++++++++++OOOOOOOOOOXXX..     ",
"    ..XXXOOOOOOOO+@@@@@@@@@@#OOOOOOOOOXXX..     ",
"    ..XXX$$$$$$$$+@@@@@@@@@@#$$$$$$$$$XXX..     ",
"    ..XXX$$$$$$$$+@@######@@#$$$$$$$$$XXX..     ",
"    ..XXX%%%%%%%%+@@#%%%%%###%%%%%%%%%XXX..     ",
"    ..XXX%%%%%%%%+@@#%%%%%%%%%%%%%%%%%XXX..     ",
"    ..XXX&&&&&&&&+@@#&&&&&&&&&&&&&&&&&XXX..     ",
"    ..XXX&&&&&&&&+@@#&&&&&&&&&&&&&&&&&XXX..     ",
"    ..XXX********+@@#*****************XXX..     ",
"    ..XXX********+@@#*****************XXX..     ",
"    ..XXX********+@@#*****++**********XXX..     ",
"    ..XXX*=*=*=*=+@@++++++@@#*=*=*=*=*XXX..     ",
"    ..XXX========+@@@@@@@@@@#=========XXX..     ",
"    ..XXX========+@@@@@@@@@@#=========XXX..     ",
"    ..XXX-=-=-=-=-##########=-=-=-=-=-XXX..     ",
"    ..XXX-----------------------------XXX..     ",
"    ..XXX-----------------------------XXX..     ",
"    ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..     ",
"    ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..     ",
"    .......................................     ",
"    .......................................     ",
"        ........;;;;;;...::::::........         ",
"        ........;;;;;;...::::::........         ",
"        ........;;;;;;...::::::........         ",
"             .....................              ",
"             .....................              ",
"                                                ",
"                                                ",
"                                                ",
"  ............................................  ",
" ...XXXX.X...XX.....XXXX..XXXX..XXXXX..XXXXX... ",
" ..X.....X..X......X.....X....X.X....X.X....... ",
"...X.....X.X.......X.....X....X.X....X.X........",
"...X.....XX....XXX.X.....X....X.XXXXX..XXXX.....",
"...X.....XXX...XXX.X.....X....X.X.X....X........",
"...X.....X..X......X.....X....X.X..X...X........",
" ..X.....X...X.....X.....X....X.X...X..X....... ",
" ...XXXX.X....X.....XXXX..XXXX..X....X.XXXXX... ",
"  ............................................  ",
"                                                "};
