/* XPM */
static char * ck_core_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"32 32 6 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor5	m black	c blue",
"X	s background	m black	c #949494949494",
"o	s topShadowColor	m white	c #bdbdbdbdbdbd",
"O	s iconColor1	m black	c black",
"+	s bottomShadowColor	m black	c #636363636363",
/* pixels */
"  ............................  ",
" .............................. ",
"....XXXXXXXXXXXXXXXXXXXXXXXX....",
"..ooooooooooooXXXooooXXXXXoooo..",
"..oOOOOOOOOOO+XXXoOOOXXXXoOOO+..",
"..oOOOOOOOOOO+XXXoOOOXXXoOOO+X..",
"..oOO+++++++++XXXoOOOXXoOOO+XX..",
"..oOO+XXXXXXXXXXXoOOOXoOOO+XXX..",
"..oOO+XXXXXXXXXXXoOOOoOOO+XXXX..",
"..oOO+XXXXXXXXXXXoOOOOOO+XXXXX..",
"..oOO+XXXXXXXXXXXoOOOOO+XXXXXX..",
"..oOO+XXXXXXXXXXXoOOOOO+XXXXXX..",
"..oOO+XXXXXXXXXXXoOOOOOO+XXXXX..",
"..oOO+XXXXXXXXXXXoOOOOOOO+XXXX..",
"..oOO+XXXXXXXXXXXoOO++oOOO+XXX..",
"..oOO+XXXXXXXXXXXoOO+XXoOOO+XX..",
"..oOOoooooooooXXXoOO+XXXoOOO+X..",
"..oOOOOOOOOOO+XXXoOO+XXXXoOOO+..",
"..oOOOOOOOOOO+XXXoOO+XXXXXoOOO..",
"..o+++++++++++XXXo+++XXXXXX+++..",
"..XXXXXXXXXXXXXXXXXXXXXXXXXXXX..",
"..XoooooXooooXXooooXXXoooooXXX..",
"..Xo+++++o++o+Xo+++o+Xo+++++XX..",
"..Xo+XXXXo+Xo+Xo+XXo+Xo+XXXXXX..",
"..Xo+XXXXo+Xo+Xoooo+XXooooXXXX..",
"..Xo+XXXXo+Xo+Xoo++XXXo++++XXX..",
"..Xo+XXXXo+Xo+Xo+o+XXXo+XXXXXX..",
"..Xo+oooXoooo+Xo+Xo+XXoooooXXX..",
"...o+++++X++++Xo+XXo+XX+++++X...",
"....XXXXXXXXXXXXXXXXXXXXXXXX....",
" .............................. ",
"  ............................  "};
