/* XPM */
static char * ck_mines_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 10 1 0 0",
/* colors */
" 	s none	m none	c none",
".	s iconColor1	m black	c black",
"X	s iconGray2	m white	c #bdbdbdbdbdbd",
"o	s iconGray4	m white	c #949494949494",
"O	s iconGray5	m black	c #737373737373",
"+	s iconGray7	m black	c #424242424242",
"@	s iconGray8	m black	c #212121212121",
"#	s iconGray1	m white	c #dededededede",
"$	s iconGray3	m white	c #adadadadadad",
"%	s iconGray6	m black	c #636363636363",
/* pixels */
"                                                ",
"                     ....                       ",
"                    .XoO+.                      ",
"                    .XoO+.                      ",
"                    .XoO+.                      ",
"                   @@@@@@@@                     ",
"         ...    @@@XXXXXXXX@@@   ...            ",
"        .#$+..@@XXXXXXXXoXXooo@@.XXo.           ",
"       .#$o%+@XX$X$XXXXXX$o$oooo@Xooo.          ",
"       .$$o%+XXXXXXXX$$ooX#oXoX$o@o%%.          ",
"        .$o@XXXXXXXoXXoXXXo$o#ooo+@%.           ",
"        ..@XXXX$XX$XXXooXoooooooo++@            ",
"         @XX$XXXX#XXXo$$oo$oo$o#o+++@           ",
"        @XXXXX$XX#XooooXooooooooo+@@@@          ",
"        @XXXXX#XXXoooXooo#o$$oooO++@@@          ",
"       @XXXX$$XXXoXoooo$oooooooOO+++@@@         ",
"       @X$XXXXXXoo#$ooooooXooooOO+++@@@         ",
"       @XXXXXXXoooooo$ooooo$oOoOO++@@@@         ",
"      @XXXXXoXXoooooo@@@ooooooO@O+@+@@@@        ",
"   ...@XXX$oXooo#ooo@XXX@ooooOOOO+++@@@@...     ",
"  @XXX@XXXXXooo#Xoo@Xooo%@oooOOO@++@@@@@XXX.    ",
"  @Xoo@X$XXXo$ooooo@Xooo%@oooOOO+++@@@@@$oo.    ",
"  @OOO@XXX$$oooo$oo@Xoo+%@ooOOO@+++@@@@@oo%.    ",
"  @O++@XXXXo#ooooooo@%%%@ooOOOO+++@@@@@@%++.    ",
"   @@@@XXX$oooo$$oooo@@@ooOOOO+++@@@+@@@...     ",
"      @XX$oooXo$o#o#oooooOOOOO+++@@@@@@@        ",
"       @XXo$oooXoooXooooOOOOO+++@@@@@@@         ",
"       @XooXooo#ooooooOOOO@%++++@@@@@@@         ",
"       @XooXooooooooOOOOO%++++@+@@+@@@@         ",
"        @ooooooooXoOOO%%%++++@@@@@@@@@          ",
"        @oooo#oooOO%%%%%++++@@@@+@@@@@          ",
"         @ooOOOOO%%%%%+++@@@@@@@@@@@@           ",
"         .@OOOOO+++++++@@@+@@@+@@@@@.           ",
"        .XX@OOO++++@+++@@@@@@@+@@@@O..          ",
"        .Xoo@++++++++@@@@@@@@@@@@@oO%.          ",
"        .ooO%@@@@@@@@@@@+@@@@@@@@oO%..          ",
"         .O%..@@@@@@@@@@@@@+@@@@..%..           ",
"          ...   @@@@@@@@@@@@@@   ...            ",
"                   @@@@@@@@                     ",
"                    .XoO+.                      ",
"                    .XoO+.                      ",
"                    .XoO+.                      ",
"                     ....                       ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
