/* XPM */
static char * nibbles_l_pm[] = {
/* width height ncolors cpp [x_hot y_hot] */
"48 48 4 1 -1 -1",
/* colors */
" 	s none	m none	c none",
".	s iconColor5	m black	c blue",
"X	s iconColor6	m white	c yellow",
"o	s iconColor8	m black	c magenta",
/* pixels */
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"     ....... ....... .......                    ",
"     ....... ....... .......                    ",
"     ....... ....... .......                    ",
"     ....... ....... .......                    ",
"     ....... ....... .......                    ",
"     ....... ....... .......                    ",
"     ....... ....... .......                    ",
"                                                ",
"     .......         .......                    ",
"     .......         .......                    ",
"     .......         .......                    ",
"     .......         .......                    ",
"     .......         .......                    ",
"     .......         .......                    ",
"     .......         .......                    ",
"                                                ",
"     .......                                    ",
"     .......           XXX                      ",
"     .......          XXXXX                     ",
"     .......          XXXXX                     ",
"     .......          XXXXX                     ",
"     .......           XXX                      ",
"     .......                                    ",
"                                                ",
"     .......                         ooooooo    ",
"     .......                         ooooooo    ",
"     .......                         ooooooo    ",
"     .......                         ooooooo    ",
"     .......                         ooooooo    ",
"     .......                         ooooooo    ",
"     .......                         ooooooo    ",
"                                                ",
"     .......         ooooooo ooooooo ooooooo    ",
"     .......         ooooooo ooooooo ooooooo    ",
"     .......         ooooooo ooooooo ooooooo    ",
"     .......         ooooooo ooooooo ooooooo    ",
"     .......         ooooooo ooooooo ooooooo    ",
"     .......         ooooooo ooooooo ooooooo    ",
"     .......         ooooooo ooooooo ooooooo    ",
"                                                ",
"                                                ",
"                                                ",
"                                                ",
"                                                "};
